# Generated by Django 4.2.13 on 2024-07-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_item_prof'),
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
