# Generated by Django 4.2.13 on 2024-07-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_loc', models.CharField(blank=True, max_length=100)),
                ('precise_loc', models.TextField()),
                ('item_desc', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='photos/')),
                ('is_published', models.BooleanField(default=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signin.profile')),
            ],
        ),
    ]
