# Generated by Django 4.2.13 on 2024-07-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='precise_loc',
            field=models.TextField(blank=True),
        ),
    ]
