# Generated by Django 4.2.13 on 2024-07-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_item_precise_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.TextField(blank=True),
        ),
    ]
