# Generated by Django 4.2.13 on 2024-07-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_item_item_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='email',
            new_name='prof',
        ),
    ]
