# Generated by Django 4.2.13 on 2024-07-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_item_desc_item_item_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_description',
            new_name='item_desc',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='precise_location',
            new_name='precise_loc',
        ),
    ]
